version: "2.15.1"

services:
  nginx: # API Gateway \ Router
    image: nginx:1.24.0
    ports:
      - 3000:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./resources:/opt/jirarush/resources
    depends_on:
      server:
        condition: service_started
    restart: always
    networks:
      - frontend_network

  db:
    image: postgres:15.2
    container_name: postgres_db
#    expose:
#      - 5432
    ports:
      - 5432:5432
    networks:
      - backend_network
    env_file:
      - env.env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - -pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 2s
      timeout: 30s
      retries: 10
    restart: always

  server:
    build: .
    container_name: jira
    env_file:
      - env.env
    networks:
      - frontend_network
      - backend_network
    ports:
      - 8080:8080
#    expose:
#      - 8080
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  -pgdata:
networks:
  backend_network:
    driver: bridge
  frontend_network:
    driver: bridge
